main: com.ramide1.mcnohit.App
name: mcnohit
version: 1.0
api-version: 1.20
commands:
  deathcount:
    description: Ver la cantidad de muertes de un jugador
    permission: mcnohit.deathcont
  nohitreload:
    description: Recargar la configuracion del plugin
    permission: mcnohit.nohitreload
  deathcountreset:
    description: Resetear las kills de un jugador
    permission: mcnohit.deathcountreset