name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: mcnohit
        path: target/mcnohit-1.0-SNAPSHOT.jar
